[project]
name = "poke-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.1",
    "httpx>=0.28.1",
    "pydantic[email]>=2.12.3",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
]
